codecov:
  max_report_age: 24h

coverage:
  precision: 2
  round: nearest
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        enabled: false
    changes:
      default:
        enabled: false
