namespace Typin.Internal.Schemas
{
    using System.Reflection;
    using Typin.Attributes;
    using Typin.Internal.Extensions;
    using Typin.Schemas;

    /// <summary>
    /// Resolves an instance of <see cref="CommandOptionSchema"/>.
    /// </summary>
    internal static class CommandOptionSchemaResolver
    {
        /// <summary>
        /// Resolves <see cref="CommandOptionSchema"/>.
        /// </summary>
        internal static CommandOptionSchema? TryResolve(PropertyInfo property)
        {
            CommandOptionAttribute? attribute = property.GetCustomAttribute<CommandOptionAttribute>();
            if (attribute is null)
                return null;

            string? name = attribute.HasAutoGeneratedName ? property.Name.ToHyphenCase() : attribute.Name;

            return new CommandOptionSchema(
                property,
                name,
                attribute.ShortName,
                attribute.FallbackVariableName,
                attribute.IsRequired,
                attribute.Description
            );
        }
    }
}