namespace Typin.Internal.Schemas
{
    using System;
    using System.Reflection;
    using Typin.Attributes;
    using Typin.Binding;
    using Typin.Internal.Exceptions;
    using Typin.Metadata;
    using Typin.Schemas;
    using Typin.Utilities;
    using Typin.Utilities.Extensions;

    /// <summary>
    /// Resolves an instance of <see cref="ParameterSchema"/>.
    /// </summary>
    internal static class ParameterSchemaResolver
    {
        /// <summary>
        /// Resolves <see cref="ParameterSchema"/>.
        /// </summary>
        public static ParameterSchema? TryResolve(PropertyInfo property)
        {
            ParameterAttribute? attribute = property.GetCustomAttribute<ParameterAttribute>();
            if (attribute is null)
            {
                return null;
            }

            string name = attribute.HasAutoGeneratedName ? TextUtils.ToKebabCase(property.Name) : attribute.Name!;

            if (attribute.Converter is Type converterType && !converterType.Implements(typeof(IBindingConverter)))
            {
                throw AttributesExceptions.InvalidConverterType(converterType);
            }

            return new ParameterSchema(
                property,
                attribute.Order,
                name,
                attribute.Description,
                attribute.Converter,
                new MetadataCollection()
            );
        }
    }
}