namespace Typin.Attributes
{
    using System;
    using Typin.Descriptors;

    /// <summary>
    /// Annotates a property that defines a command parameter.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class ParameterAttribute : Attribute, IParameterDescriptor
    {
        /// <inheritdoc/>
        public int Order { get; }

        /// <summary>
        /// Parameter name, which is only used in help text.
        /// If this isn't specified, kebab-cased property name is used instead.
        /// </summary>
        public string? Name { get; init; }

        /// <inheritdoc/>
        public string? Description { get; init; }

        /// <summary>
        /// Whether option has auto generated name.
        /// </summary>
        public bool HasAutoGeneratedName => Name is null;

        /// <inheritdoc/>
        public Type? Converter { get; init; }

        /// <summary>
        /// Initializes an instance of <see cref="ParameterAttribute"/>.
        /// </summary>
        public ParameterAttribute(int order)
        {
            Order = order;
        }
    }
}