namespace Typin.Attributes
{
    using System;
    using Typin.Descriptors;

    /// <summary>
    /// Annotates a property that defines a command option.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class OptionAttribute : Attribute, IOptionDescriptor
    {
        /// <summary>
        /// Option name (must be longer than a single character). Starting dashes are trimed automatically.
        /// All options in a command must have different names (comparison is case-sensitive).
        /// If this isn't specified, kebab-cased property name is used instead.
        /// </summary>
        public string? Name { get; }

        /// <inheritdoc/>
        public char? ShortName { get; }

        /// <inheritdoc/>
        public bool IsRequired { get; init; }

        /// <inheritdoc/>
        public string? Description { get; init; }

        /// <inheritdoc/>
        public string? FallbackVariableName { get; init; }

        /// <summary>
        /// Whether option has auto generated name.
        /// </summary>
        public bool HasAutoGeneratedName => Name is null && ShortName is null;

        /// <inheritdoc/>
        public Type? Converter { get; init; }

        /// <summary>
        /// Initializes an instance of <see cref="OptionAttribute"/>.
        /// </summary>
        private OptionAttribute(string? name, char? shortName)
        {
            Name = name;
            ShortName = shortName;
        }

        /// <summary>
        /// Initializes an instance of <see cref="OptionAttribute"/>.
        /// </summary>
        public OptionAttribute(string name, char shortName)
            : this(name, (char?)shortName)
        {

        }

        /// <summary>
        /// Initializes an instance of <see cref="OptionAttribute"/>.
        /// </summary>
        public OptionAttribute(string name)
            : this(name, null)
        {

        }

        /// <summary>
        /// Initializes an instance of <see cref="OptionAttribute"/>.
        /// </summary>
        public OptionAttribute()
            : this(null, null)
        {

        }

        /// <summary>
        /// Initializes an instance of <see cref="OptionAttribute"/>.
        /// </summary>
        public OptionAttribute(char shortName)
            : this(null, (char?)shortName)
        {

        }
    }
}