name: Typin-CI

on:
  push:
    branches:
      - master
      - develop
    tags-ignore:
      - '*'
    paths-ignore:
      - 'src/TypinExamples/*'
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'develop-examples-app'
    tags-ignore:
      - '*'
    paths-ignore:
      - 'src/TypinExamples/*'
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Build & test
      run: dotnet test src/Typin/Typin.sln --configuration Release-CI

    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./src/Typin/Typin.Tests/bin/Release/Coverage.xml
