name: Typin-CD

on:
  push:
    tags:
    - 'Typin-[0-9]+.[0-9]+.[0-9]+'
    - 'Typin-[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+'
    - 'Typin-[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x

    - name: Pack
      run: dotnet pack src/Typin/Typin.sln --configuration Release-CD

    - name: Deploy
      run: dotnet nuget push src/Typin/Typin/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}

    - name: Deploy
      run: dotnet nuget push src/Typin/Typin.Core/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
