name: Typin-CD

on:
  push:
    tags:
    - 'Typin-[0-9]+.[0-9]+.[0-9]+'
    - 'Typin-[0-9]+.[0-9]+.[0-9]+-dev-[0-9]+'
    - 'Typin-[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Install .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x

    - name: Pack
      run: dotnet pack Typin/src/Typin.sln --configuration Release-CD

    - name: Deploy
      run: |
        dotnet nuget push Typin/src/Typin/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Core/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Console/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help.Abstractions/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help.Modes.Interactive/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help.Modes.Programmatic/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help.Modes.Utilities/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help.Modes.Utilities.CommandLine/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
        dotnet nuget push Typin/src/Typin.Help.Modes.Utilities.ExceptionFormatter/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}
